const SETTINGS = "SETTINGS";
const CURRENT_WEATHER = "CURRENT_WEATHER";
const FORECAST = "FORECAST"

export default Object.freeze({ SETTINGS, CURRENT_WEATHER, FORECAST });
export { SETTINGS, CURRENT_WEATHER, FORECAST };
